server:
  port: 8004

ftp:
  nginx: http://10.10.62.8/jw/

spring:
  application:
    name: user-center #微服务应用的名字
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource #当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver #mysql驱动包
    url: jdbc:mysql://192.168.19.128:3306/file_center?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9099/eureka


mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.example.entity
